#!/usr/bin/env bash
# Installs nginx and set a default messasge
# port 80 as a default

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/HTTP/html/index.html
service nginx start
