#!/bin/bash

# Replace [STUDENT_ID] with your actual student ID
STUDENT_ID=[STUDENT_ID]

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo sed -i 's/ENABLED=.*/ENABLED=1/' /etc/default/haproxy

cat <<EOT | sudo tee /etc/haproxy/haproxy.cfg
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 18.207.233.231-web-01:80 check
    server web-02 54.82.173.157-web-02:80 check
EOT

# Restart HAProxy
sudo systemctl restart haproxy

# Configure server hostnames
sudo hostnamectl set-hostname ${STUDENT_ID}-web-01
echo "127.0.0.1 18.207.233.231-web-01" | sudo tee -a /etc/hosts
sudo hostnamectl set-hostname ${STUDENT_ID}-web-02
echo "127.0.0.1 54.82.173.157-web-02" | sudo tee -a /etc/hosts

